In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('production_analysis_dataset.csv')
df.sample(10)

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183

In [6]:
df.groupby('product_category')['units_produced'].sum()

product_category
Automotive     9408
Electronics    7491
Furniture      7251
Name: units_produced, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   production_id           50 non-null     int64
 1   product_category        50 non-null     object
 2   factory                 50 non-null     object
 3   shift                   50 non-null     object
 4   supervisor              50 non-null     object
 5   units_produced          50 non-null     int64
 6   defective_units         50 non-null     int64
 7   production_time_hr      50 non-null     float64
 8   machine_downtime_hr     50 non-null     float64
 9   energy_consumption_kwh  50 non-null     int64
 10  profit                  50 non-null     int64
dtypes: float64(2), int64(5), object(4)
memory usage: 4.4+ KB

In [25]:
df.groupby('factory')['profit'].mean()

factory
Plant_A    18044.375000
Plant_B    16973.384615
Plant_C    18086.076923
Name: profit, dtype: float64

In [26]:
df.groupby('shift')['defective_units'].sum()

shift
Evening    132
Morning    472
Night      471
Name: defective_units, dtype: int64

In [21]:
df.head()

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045

In [27]:
df.groupby('supervisor')['production_time_hr'].mean()

supervisor
S1    7.801818
S2    7.450000
S3    7.882000
S4    7.956154
Name: production_time_hr, dtype: float64

In [35]:
df.groupby(['factory','shift'])['energy_consumption_kwh'].sum()

factory  shift
Plant_A  Evening     3330
         Morning    11144
         Night      12913
Plant_B  Evening     2889
         Morning     7923
         Night       4981
Plant_C  Evening     2214
         Morning     5632
         Night       7363
Name: energy_consumption_kwh, dtype: int64

In [38]:
df.groupby('product_category').agg(['sum','max','min','mean'])

TypeError: agg function failed [how->mean,dtype->object]