In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Employee_Attrition.csv')
df.head()

,Employee_ID,Age,Monthly_Income,Years_at_Company,Job_Role,Work_Life_Balance,Overtime,Job_Satisfaction,Distance_From_Home,Education,Attrition
0,1,29,23278,8,Manager,Poor,Yes,1,22,Postgraduate,1
1,2,56,31395,18,HR,Poor,Yes,1,7,School,1
2,3,54,98907,0,Manager,Excellent,No,2,15,Postgraduate,0
3,4,39,20851,5,HR,Good,No,2,7,Graduate,0
4,5,28,32156,12,Developer,Good,No,3,26,School,0

In [3]:
df.isna().sum()

Employee_ID           0
Age                   0
Monthly_Income        0
Years_at_Company      0
Job_Role              0
Work_Life_Balance     0
Overtime              0
Job_Satisfaction      0
Distance_From_Home    0
Education             0
Attrition             0
dtype: int64

In [4]:
df=df.drop('Employee_ID',axis=1)
df.head()

,Age,Monthly_Income,Years_at_Company,Job_Role,Work_Life_Balance,Overtime,Job_Satisfaction,Distance_From_Home,Education,Attrition
0,29,23278,8,Manager,Poor,Yes,1,22,Postgraduate,1
1,56,31395,18,HR,Poor,Yes,1,7,School,1
2,54,98907,0,Manager,Excellent,No,2,15,Postgraduate,0
3,39,20851,5,HR,Good,No,2,7,Graduate,0
4,28,32156,12,Developer,Good,No,3,26,School,0

In [5]:
df=pd.get_dummies(df,drop_first=True)
df.sample(5)

,Age,Monthly_Income,Years_at_Company,Job_Satisfaction,Distance_From_Home,Attrition,Job_Role_Developer,Job_Role_HR,Job_Role_Manager,Work_Life_Balance_Good,Work_Life_Balance_Poor,Overtime_Yes,Education_Postgraduate,Education_School
230,45,87499,17,4,4,0,True,False,False,True,False,True,False,False
193,45,49430,0,2,5,0,False,False,False,False,True,False,False,True
129,60,66179,7,2,21,0,False,False,True,False,False,False,False,True
243,45,63416,3,1,20,0,False,True,False,False,False,False,False,False
40,28,117310,17,2,23,0,False,False,True,True,False,False,False,False

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x=df.drop(columns=['Attrition'])
y=df['Attrition']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((200, 13), (50, 13), (200,), (50,))

In [9]:
from sklearn.svm import SVC
clf=SVC(kernel='rbf',C=1,random_state=42)
clf.fit(x_train,y_train)

SVC(C=1, random_state=42)

In [10]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[47,  0],
       [ 3,  0]])

In [12]:
tn=cm[0][0]
fp=cm[0][1]
fn=cm[1][0]
tp=cm[1][1]
tn,fn,tp,fp

(np.int64(47), np.int64(3), np.int64(0), np.int64(0))

In [13]:
accuracy=(tn+tp)/(tn+fn+fp+tp)
error_rate=(fn+fp)/(tn+fn+fp+tp)
sensitivity =tp/(tp+fn)
specificity=tn/(tn+fp)
precision=tp/(tp+fp)
print(f"accuracy = {accuracy}\nerror rate = {error_rate}\nsensitivity = {sensitivity}\nspecificity = {specificity}\nprecision = {precision}")

accuracy = 0.94
error rate = 0.06
sensitivity = 0.0
specificity = 1.0
precision = nan

C:\Users\LJENG\AppData\Local\Temp\ipykernel_15460\2840515854.py:5: RuntimeWarning: invalid value encountered in scalar divide
  precision=tp/(tp+fp)

In [14]:
df.sample()

,Age,Monthly_Income,Years_at_Company,Job_Satisfaction,Distance_From_Home,Attrition,Job_Role_Developer,Job_Role_HR,Job_Role_Manager,Work_Life_Balance_Good,Work_Life_Balance_Poor,Overtime_Yes,Education_Postgraduate,Education_School
143,60,20371,8,2,4,0,False,False,True,False,True,False,True,False

In [15]:
clf.predict([[30,45000,5,3,10,True,False,False,True,False,True,False,0,]])

C:\ProgramData\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([0])