In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [2]:
df=pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
df=pd.get_dummies(df,drop_first=True)
df.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [5]:
y=df['charges']
x=df.drop(columns=['charges'])

In [6]:
te=[0.1,0.2,0.3,0.4,0.5]

In [7]:
columns = ['test_size','random_state','MSE']
d = pd.DataFrame(columns=columns)
d

Empty DataFrame
Columns: [test_size, random_state, MSE]
Index: []

In [9]:
t=[]
r=[]
mse=[]
for i in te:
    for j in range(1,51):
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=i,random_state=j)
        #print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)
        lr=LinearRegression()
        lr.fit(x_train,y_train)
        mse1=mean_squared_error(y_test,lr.predict(x_test))
        mse.append(mse1)
        t.append(i)
        r.append(j)

In [10]:
d=pd.DataFrame({
            'test_size':t,'random_state':r,'MSE':mse
        })

In [11]:
d

     test_size  random_state           MSE
0          0.1             1  4.310428e+07
1          0.1             2  3.390603e+07
2          0.1             3  3.953055e+07
3          0.1             4  3.989601e+07
4          0.1             5  3.123167e+07
..         ...           ...           ...
245        0.5            46  3.709951e+07
246        0.5            47  3.421207e+07
247        0.5            48  3.501140e+07
248        0.5            49  3.625376e+07
249        0.5            50  3.444655e+07

[250 rows x 3 columns]

In [13]:
d['MSE'].min()

25965692.541817248

In [14]:
d[d['MSE']==d['MSE'].min()]

    test_size  random_state           MSE
35        0.1            36  2.596569e+07